name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # Triggers the workflow when pushing to the `main` branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.MY_SECRET }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/potajito/steamloggd:latest .

      # Push the Docker image to GHCR
      - name: Push Docker image
        run: docker push ghcr.io/potajito/steamloggd:latest